---
# tasks file for apache2
- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Start service apache2, if not started
  ansible.builtin.service:
    name: apache2
    state: started

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'
    notify: Restart service Apache2, in all cases
